spring.application.name=finance_tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=vinialb
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
